#
# Automagically generated by Approximatrix Simply Fortran 2.39
#
FC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\ar.exe"
WRC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\windres.exe"
RM=rm -f

IDIR=

LDIR=


OPTFLAGS= -g -mtune=broadwell

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS= -fopenmp -std=legacy

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\etpred.o": ".\etpred.f90"
	@echo Compiling .\etpred.f90
	@$(FC) -c -o "build\etpred.o" $(FFLAGS) ".\etpred.f90"
"modules\params.mod" "modules\max_pars.mod" "modules\ddt_mod.mod" "modules\control3.mod" "modules\control4.mod" "modules\tidphas.mod" "modules\tidwave1.mod" "modules\tidwave2.mod" "modules\love.mod" "modules\inout.mod" : "build\etpred.o" .EXISTSONLY
	@echo Compiling .\etpred.f90
	@$(FC) -c -o "build\etpred.o" $(FFLAGS) ".\etpred.f90"

clean: .SYMBOLIC
	@echo Deleting build\etpred.o and related files
	@$(RM) "build\etpred.o" "modules\params.mod" "modules\max_pars.mod" "modules\ddt_mod.mod" "modules\control3.mod" "modules\control4.mod" "modules\tidphas.mod" "modules\tidwave1.mod" "modules\tidwave2.mod" "modules\love.mod" "modules\inout.mod"
	@echo Deleting predictk.exe
	@$(RM) "predictk.exe"

"predictk.exe":  "build\etpred.o" "build\predictk.prj.target"
	@echo Generating predictk.exe
	@$(FC) -o "predictk.exe" -static -fopenmp "build\etpred.o" $(LDIR) $(PRJ_LFLAGS)

all: "predictk.exe" .SYMBOLIC

