name: wheels
on:
  push:
    branches:
      - master
      - wheels

concurrency:
  group: wheels-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: build (${{ matrix.os }}, ${{ matrix.build }})
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BUILD: '${{ matrix.build }}-*'
      CIBW_SKIP: '*i686 *win32 *s390x *ppc64le *musllinux* *aarch64'
      CIBW_BEFORE_BUILD_MACOS: 'pip install numpy setuptools<60 && ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran && gfortran --version'
      CIBW_BEFORE_BUILD_WINDOWS: 'pip install numpy setuptools<60 && cd {package} && echo >> setup.cfg && echo [build_ext] >> setup.cfg && echo compiler=mingw32 >> setup.cfg  && echo fcompiler=gnu95 >> setup.cfg && cat setup.cfg'
      CIBW_BEFORE_BUILD_LINUX: 'pip install numpy setuptools<60'
      #CIBW_ENVIRONMENT: SETUPTOOLS_USE_DISTUTILS=stdlib
      CIBW_BUILD_VERBOSITY: 1
      CIBW_TEST_COMMAND: python -c "import pygtide; pygtide.test(); pygtide.update(); pygtide.test()"
    strategy:
      # for pushes to master, we only build a subset of wheels
      # this does not apply to tags
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build: [cp37, cp38, cp39, cp310]
        exclude-flag:
          - ${{ github.ref_name == 'wheels' && github.event_name == 'push' }}
        exclude:
          - build: cp38
            exclude-flag: true
          - build: cp39
            exclude-flag: true
    steps:
      - uses: actions/checkout@v3

      - name: Print environment variables
        shell: bash -l {0}
        run: |
          echo "CIBW_BUILD: $CIBW_BUILD"
          echo "CIBW_SKIP: $CIBW_SKIP"
          echo "CIBW_TEST_COMMAND: $CIBW_TEST_COMMAND"

      - name: Build and test wheels
        uses: pypa/cibuildwheel@2.5.0

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
